### ISSUE TITLE
Support for Http API

### ISSUE THREAD

**Issue by jcarter3** [awslabs/aws-lambda-go-api-proxy#60]
Are there plans to support the Http API v2 events?

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

**Comment by charlietran** [comment]
V2 support would be great! Currently, HTTP API is working fine for us with this library, as long as we set the PayloadFormat in our Lambda Integration to `1.0`. Cloudformation YAML example:

```yaml
  HttpApiInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref YourHttpApi
      PayloadFormatVersion: '1.0'
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ''
        - - !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/
          - !GetAtt YourAPILambdaFunction.Arn
          - /invocations
      TimeoutInMillis: 15000
```
